// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/employee.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	EmployeeId           int32    `protobuf:"varint,1,opt,name=EmployeeId,proto3" json:"EmployeeId,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_f51afe6743d989cb, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Employee)(nil), "main.Employee")
}

func init() { proto.RegisterFile("proto/employee.proto", fileDescriptor_f51afe6743d989cb) }

var fileDescriptor_f51afe6743d989cb = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x2d, 0xc8, 0xc9, 0xaf, 0x4c, 0x4d, 0xd5, 0x03, 0x73, 0x85, 0x58, 0x72,
	0x13, 0x33, 0xf3, 0x94, 0xca, 0xb8, 0x38, 0x5c, 0xa1, 0xe2, 0x42, 0x72, 0x5c, 0x5c, 0x30, 0xb6,
	0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x92, 0x88, 0x90, 0x0c, 0x17, 0xa7, 0x5b,
	0x66, 0x51, 0x71, 0x89, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42,
	0x40, 0x48, 0x8a, 0x8b, 0xc3, 0x27, 0x11, 0x2a, 0xc9, 0x0c, 0x96, 0x84, 0xf3, 0x85, 0x04, 0xb8,
	0x98, 0x1d, 0xd3, 0x53, 0x25, 0x58, 0xc0, 0x46, 0x82, 0x98, 0x49, 0x6c, 0x60, 0x47, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x20, 0x2f, 0x30, 0x9c, 0x00, 0x00, 0x00,
}
